steps:
  - id: "Teste unitário"
    name: 'golang'
    args: ['go', 'test', './go']

  - id: "Build image"
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/devops-k8s-go:latest', './go']

images:
  - 'gcr.io/$PROJECT_ID/devops-k8s-go'