apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-k8s
data:
  index.html: |

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Code.education Rocks</title>
    </head>
    <body>
      <h1>Code.education Rocks</h1>
    </body>
    </html>